/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    id("war")
    id("application")
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("javax.servlet:javax.servlet-api:3.1.0")
    implementation("log4j:log4j:1.2.17")
}

group = "Log4jEnableDisableEx"
version = "0.0.1-SNAPSHOT"
description = "Log4jEnableDisableEx Maven Webapp"
java.sourceCompatibility = JavaVersion.VERSION_1_8
java.targetCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
