language: groovy
jdk:
  - oraclejdk8

install: true
script: ./gradlew build --info --full-stacktrace --no-daemon

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew publishPlugins
  on:
    branch: master
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_64269f8d357f_key -iv $encrypted_64269f8d357f_iv
  -in gradle.properties.enc -out gradle.properties -d
